# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170720_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='author_id',
        ),
    ]
