# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_wiki_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='status',
        ),
    ]
