# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20170725_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
