# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170824_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.AuthSource'),
        ),
    ]
