# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
